# Deploy latest commit to the server
- hosts: all
  roles:
    - common
  vars:
    HOST: '{{ inventory_hostname }}'
    PYTHON_VERSION: 'python3.8'
    MAIN_APP_NAME: "project4"
    REPO_URL: "https://github.com/kevinbeirne1/CS50W-Projects.git"
    REPO_BRANCH: "Project_4-Network"

