name: Django CI

on:
  push:
    branches: [ Project_4-Network ]
  pull_request:
    branches: [ Project_4-Network ]


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Run tests
        run: |
          python manage.py test
